create database customer_behavior;
use customer_behavior;
select * from customer;

-- Q1 Total revenue generated by various age groups
select age_group, 
concat("$ ",round(sum(purchase_amount)/1000,2),"k") as revenue
from customer
group by age_group;

-- Q2 Customers using a discount still spending more than average purchase amount
select customer_id, purchase_amount
from customer
where discount_applied = "Yes"
and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3 Top 5 products with highest average review rating
select item_purchased, round(avg(review_rating),2) as Average_product_rating
from customer group by item_purchased order by Average_product_rating desc limit 5;

-- Q4 Average shipping amount across shipping_types
select shipping_type, concat("$ ",round(avg(purchase_amount),2)) as amount
from customer group by shipping_type;

-- Q5 Do subscribed customers buy more? Compare average spend and total revenue between subscribers and non subscribers.
select subscription_status, count(customer_id) as Total_customers,
round(avg(purchase_amount),2) as average_spending,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by 3,4 desc;

-- Q6 5 products have the highest percentage of purchases with discounts applied
select item_purchased, 
concat(round(sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) * 100,2), " %") as discount_rate
from customer group by item_purchased
order by discount_rate desc
limit 5;

-- Q7 Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
case when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customer)

select customer_segment, count(*) as Number_of_customers
from customer_type
group by customer_segment;

-- Q8 Top 3 most purchased products within each category
with item_counts as (
select category, item_purchased, count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank<=3;

-- Q9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group  by subscription_status;

-- Q10 What is the revenue contribution of each gender
select gender, concat("$ ",round(sum(purchase_amount)/1000,2),"k") as revenue
from customer group by gender;